

export const dbTables = [
    'Action',
    'Ancestry',
    'Archetype',
    'Armor',
    'Background',
    'Class',
    'Condition',
    'Creature',
    'Speed',
    'SkillMod',
    'Resistance',
    'CreatureFamily',
    'Deity',
    'Equipment',
    'Feat',
    'Hazard',
    'Ritual',
    'Rule',
    'Shield',
    'Skill',
    'Source',
    'Spell',
    'Weapon',
    'WeaponGroup',
    'WeaponType',
    'WeaponCategory',
    'SavingThrow',
    'PatronTheme',
    'Mystery',
    'Lesson',
    'Component',
    'Bloodline',
    'AreaType',
    'HazardType',
    'Heighten',
    'Usage',
    'Frequency',
    'Element',
    'Ammunition',
    'Sanctification',
    'DomainAlternate',
    'Pantheon',
    'Domain',
    'DivineFont',
    'DeityCategory',
    'AreaOfConcern',
    'WeaknessType',
    'Tradition',
    'SpeedType',
    'Size',
    'Sense',
    'School',
    'ResistanceType',
    'Immunity',
    'CreatureAbility',
    'Alignment',
    'Region',
    'ArmorGroup',
    'ItemCategory',
    'ItemSubCategory',
    'ArmorCategory',
    'ElementType',
    'PFS',
    'ArchetypeCategory',
    'SourceCategory',
    'SourceGroup',
    'Vision',
    'Rarity',
    'Attribute',
    'Language',
    'TraitGroup',
    'Trait',
    'Weakness'
    ]


const pc = [
        "3D Flanking",
"3D Movement",
"AC Bonus",
"Actions with Triggers",
"Actions",
"Activities in Encounters",
"Activities",
"Adding Damage Dice",
"Additional Feats",
"Advancement Table",
"Adventuring Gear",
"Aerial Combat",
"Afflictions",
"Age",
"Alchemical Bombs",
"Alchemical Gear",
"Alchemical Tools",
"Ammunition",
"Ancestry Entries",
"Ancestry Feats",
"Ancestry, Background, Class, or Details",
"Animal Companions",
"Animals",
"Appendices",
"Aquatic Combat",
"Archetypes",
"Area",
"Areas",
"Armor Class (AC)",
"Armor Class",
"Armor Specialization Effects",
"Armor Statistics",
"Armor Traits",
"Armor and Skills",
"Armor",
"Assistive Items",
"Attack Rolls",
"Attacking with a Shield",
"Attacking",
"Attribute Boosts & Flaws",
"Attribute Boosts",
"Attribute Modifier",
"Backgrounds",
"Barding",
"Basic Actions",
"Basic Saving Throws",
"Basics of Play",
"Bonuses",
"Bright Light",
"Bulk Conversions for Different Sizes",
"Bulk Limits",
"Bulk Values",
"Bulk of Coins",
"Bulk of Creatures",
"Bulk",
"Burrow Speed",
"Burst",
"Cantrips",
"Carrying Items",
"Casting Rituals",
"Casting Spells",
"Category",
"Changeling",
"Changing Edicts and Anathema",
"Chapter 1: Introduction",
"Chapter 2: Ancestries & Backgrounds",
"Chapter 3: Classes",
"Chapter 4: Skills",
"Chapter 5: Feats",
"Chapter 6: Equipment",
"Chapter 7: Spells",
"Chapter 8: Playing the Game",
"Character Creation",
"Check Penalty",
"Checks",
"Class DC",
"Class Feats",
"Class Features",
"Climb Speed",
"Coins and Currency",
"Communication",
"Companion Advancement",
"Companion Types",
"Companions",
"Compare to AC",
"Concealed",
"Condition Values",
"Conditions Appendix",
"Cone",
"Cost of Living",
"Cost",
"Costs and Loci",
"Counteracting",
"Counting Damage Dice",
"Cover and Large Creatures",
"Cover",
"Creating a Narrative",
"Creatures of Different Sizes",
"Critical Hits",
"Critical Specialization",
"Damage Rolls",
"Damage and Conditions",
"Damage",
"Darkness",
"Darkvision and Greater Darkvision",
"Death Effects",
"Death",
"Dedication Details",
"Defenses",
"Defining Characters",
"Deities",
"Deity",
"Describing Heroic Deeds",
"Detecting Creatures",
"Dexterity Modifier Cap (Dex Cap)",
"Diagonal Movement",
"Difficult Terrain",
"Dim Light",
"Dismissing",
"Disrupted and Lost Spells",
"Disrupting Actions",
"Donning and Removing Armor",
"Doubling and Halving Damage",
"Downtime Mode",
"Downtime",
"Dragging",
"Drawing and Stowing Items",
"Drowning and Suffocating",
"Duration",
"Durations",
"Dying",
"Earning Income",
"Edicts and Anathema",
"Effect",
"Effects",
"Elixirs",
"Emanation",
"Encounter Mode",
"Encounters",
"Estimating an Item’s Bulk",
"Example of Play",
"Exploration Activities",
"Exploration Mode",
"Exploration and Downtime Activities",
"Exploration",
"Faith",
"Faiths and Philosophies",
"Falling Objects",
"Falling on a Creature",
"Falling",
"Familiar Abilities",
"Familiars",
"Fast Healing and Regeneration",
"Feats that Grant Feats",
"Feats",
"Flanking",
"Fly Speed",
"Focus Points from Multiple Sources",
"Focus Spells",
"Forced Movement",
"Format of Rules",
"Format",
"Formulas",
"Free Actions",
"Gaining and Losing Actions",
"Gaming Is for All",
"Gear Statistics",
"Gear",
"Gender and Pronouns",
"General Feats",
"General Skill Actions",
"Getting Knocked Out",
"Getting a DC from a Modifier",
"Goals",
"Golarion and the Inner Sea",
"Grid Movement",
"Group",
"HP (BT)",
"Hands",
"Hardness",
"Hazardous Terrain",
"Heightened Spells",
"Heightened Spontaneous Spells",
"Heritages",
"Hero Points",
"Hidden",
"Hit Points, Healing, and Dying",
"Hit Points",
"Hostile Actions",
"Identifying Spells",
"Ignore Difficult Terrain",
"Immunity to Critical Hits",
"Immunity to Nonlethal",
"Immunity, Weakness, and Resistance",
"Immunity",
"Imprecise Senses",
"Improvised Weapons",
"In This Book",
"Inclines",
"Increasing Die Size",
"Initial Proficiencies",
"Innate Spells",
"Instant Death",
"Interact",
"Invisible",
"Item Crafting",
"Item Damage",
"Item Level",
"Items and Hit Points",
"Items and Sizes",
"Items of Different Sizes",
"Key Attribute",
"Languages",
"Learning Rituals",
"Leveling Up",
"Light",
"Limitations on Triggers",
"Line of Effect",
"Line of Sight",
"Line",
"Lineage Feats",
"Long Casting Times",
"Long Durations",
"Long-Term Rest",
"Losing the Dying Condition",
"Low-Light Vision",
"Making Choices",
"Massive Damage",
"Master Abilities",
"Mature Animal Companions",
"Maximum Duration",
"Melee Strikes and Ranged Strikes",
"Mixed Ancestry Heritages",
"Mixed Ancestry",
"Modes of Play",
"Modifiers and AC",
"Mounted Attacks",
"Mounted Combat",
"Mounted Defenses",
"Movement Types",
"Movement",
"Moving Through a Creature’s Space",
"Multiclass Dedications",
"Multiple Attack Penalty",
"Multiple Exposures",
"Name and Traits",
"Narrow Surfaces",
"Natural 1 and Natural 20",
"Nimble Animal Companions",
"Non-Spellcasters with Focus Spells",
"Nonlethal Attacks",
"Object Immunities",
"Objects",
"Observed",
"Onset",
"Other Actions",
"Other Activities",
"Other Currency",
"Overriding Conditions",
"Penalties",
"Perception and Detection",
"Perception for Initiative",
"Perception",
"Persistent Damage",
"Planar Scions: Nephilim",
"Playing a Versatile Heritage",
"Playing the Class",
"Playing the Game",
"Precise Senses",
"Prepared Spells",
"Price",
"Prone and Incapacitated Creatures",
"Range Penalty",
"Range and Reach",
"Range",
"Ranges, Areas, and Targets",
"Reactions in Encounters",
"Reactions",
"Reading Class Entries",
"Reading Rules",
"Reading Spells",
"Recovery Checks",
"Regional Languages",
"Release",
"Religion",
"Reload",
"Removing Afflictions",
"Required Edicts and Anathema",
"Resistance",
"Rest and Daily Preparations",
"Retraining",
"Rituals",
"Rolling Checks",
"Rules Overview",
"Sample Character",
"Savage Animal Companions",
"Saving Throw",
"Saving Throws",
"Scent",
"Secondary Casters",
"Secondary Checks",
"Secret Checks",
"Selecting Familiar and Master Abilities",
"Senses",
"Services",
"Setting Triggers",
"Shield Statistics",
"Shields",
"Shoddy Items",
"Shopping and Crafting",
"Sign Language",
"Single Actions",
"Size, Space, and Reach",
"Size",
"Skill Actions",
"Skill Checks and DCs",
"Skill Checks",
"Skill Feats",
"Skill Increases",
"Skills",
"Special Abilities",
"Special Archetypes",
"Special Battles",
"Special Circumstances",
"Special Senses",
"Specialized Animal Companions",
"Specialty Basic Actions",
"Speed Penalty",
"Speed",
"Spell Attack Rolls",
"Spell Attacks",
"Spell DC",
"Spell Slots",
"Spellcasters with Focus Spells",
"Spellcasting Archetypes",
"Spellcasting",
"Spells",
"Spontaneous Spells",
"Stages",
"Step 1: Create a Concept",
"Step 1: Roll D20",
"Step 1: Roll Damage Dice",
"Step 1: Roll Initiative",
"Step 1: Start Your Turn",
"Step 10: Finishing Details",
"Step 10",
"Step 2: Act",
"Step 2: Calculate Result",
"Step 2: Damage Type",
"Step 2: Play a Round",
"Step 2: Start Building Attribute Modifiers",
"Step 3: Apply Immunities, Weaknesses, and Resistances",
"Step 3: Begin the Next Round",
"Step 3: Compare to DC",
"Step 3: End Your Turn",
"Step 3: Select an Ancestry",
"Step 3",
"Step 4: Degree of Success",
"Step 4: End the Encounter",
"Step 4: Pick a Background",
"Step 4: Reduce Hit Points",
"Step 4",
"Step 5: Choose a Class",
"Step 5",
"Step 6: Finish Attribute Modifiers",
"Step 6",
"Step 7: Record Class Details",
"Step 7",
"Step 8: Buy Equipment",
"Step 8",
"Step 9: Calculate Modifiers",
"Step 9",
"Steps 1 and 2",
"Strength",
"Structure",
"Sustaining Spells",
"Swim Speed",
"Tactical Movement",
"Taking Damage",
"Targets",
"Temporary Hit Points",
"Temporary Immunity",
"Terrain",
"The Age of Lost Omens",
"The Flow of the Game",
"The Game Master",
"The Inner Sea Region",
"The Pathfinder Baseline",
"The Players",
"Tools of Play",
"Touch Range",
"Traits",
"Transportation",
"Travel Speed",
"Tremorsense",
"Turns",
"Unarmed Attacks",
"Understanding Actions",
"Undetected",
"Uneven Ground",
"Unlimited Possibilities!",
"Unnoticed",
"Using this book",
"Vague Senses",
"Versatile Heritages",
"Virulent Afflictions",
"Walls",
"Weakness",
"Weapon Statistics",
"Weapon Traits",
"Weapons",
"Wearing Toolkits",
"What Does My Character Know?",
"What is a Roleplaying Game?",
"Wielding Items",
"Young Animal Companions",
"Your Allies"
]

const gmc = [
    "A Proper End",
"A Welcoming Environment",
"Ability Apex",
"Access Entries",
"Accomplishments",
"Accumulating Rolls",
"Accumulating Victory Points",
"Action Economy",
"Activated Ammunition",
"Activating Elixirs",
"Activating Invested Items",
"Activating Items",
"Activation Actions",
"Active Abilities",
"Ad Hoc Bonuses and Penalties",
"Additional Knowledge",
"Adjudicating Actions",
"Adjudicating Rules",
"Adjudication",
"Adjusting Difficulty",
"Adjusting Encounters",
"Adjusting Items and Treasure",
"Adjusting Treasure",
"Admired",
"Advancing a Relic",
"Adventure Design",
"Adventure Recipes",
"Adversaries and Hazards",
"Adverse Weather and Terrain",
"Aerial Combat",
"Affixed",
"Affixing a Talisman",
"Afflictions",
"Aid",
"Alchemical Bombs",
"Alchemical Elixirs",
"Alchemical Items",
"Alchemical Poisons",
"Alchemical Tools",
"Alchemical",
"Alchemy",
"Alternative Initiative Skills",
"Alternative Skills",
"Ammunition",
"Apex Items",
"Apprentice Option",
"Aquatic Combat",
"Aquatic",
"Arctic",
"Armor & Armaments",
"Armor Class",
"Armor and Weapons",
"Armor",
"Art Objects",
"Artifact Destruction",
"Artifact Rules",
"Artifacts",
"Ash",
"At the First Session",
"Attack Potency",
"Attacking a Hazard",
"Attacking with a Staff",
"Attention Span",
"Attribute Modifiers",
"Automatic Bonus Progression",
"Avalanches",
"Average Progress",
"Awareness Points",
"Background Relics",
"Base of Operations",
"Basic Magic Armor",
"Basic Magic Weapon",
"Basic Structures",
"Basics of Ability Design",
"Batch Initiative",
"Betrayal",
"Beyond the Inner Sea",
"Blindness or Impaired Vision",
"Blizzards",
"Bogs",
"Bonuses",
"Bottom Up",
"Brief Campaign",
"Broken Vehicles",
"Budgeting for Terrain",
"Building Characters",
"Building Creatures",
"Building Hazards",
"Building Items",
"Building NPCs",
"Building Routines",
"Building Settlements",
"Building Worlds",
"Building a Character",
"Building a Chase",
"Building a Research Challenge",
"Building an Infiltration",
"Burial",
"Buying and Selling Items",
"Campaign Length",
"Campaign Relics",
"Campaign Structure",
"Campaigns without Downtime",
"Canopies",
"Cast a Spell",
"Casting Cantrips from a Staff",
"Casting Spells from a Staff",
"Casting Spells from a Wand",
"Casting a Spell from a Scroll",
"Challenges",
"Changing a Settlement",
"Changing the World",
"Chapter 1: Running the Game",
"Chapter 2: Building Games",
"Chapter 3: Age of Lost Omens",
"Chapter 4: Subsystems",
"Chapter 5: Treasure Trove",
"Character Creation",
"Characters with Disabilities",
"Chases",
"Chasms",
"Checks",
"Choosing Adversaries’ Actions",
"Choosing Creatures",
"Choosing Variant Rules",
"Choosing Your Tools",
"Civilization",
"Cliffs",
"Climate",
"Cohorts and New PCs",
"Collapses",
"Combat Duels",
"Combat Threats",
"Combining and Separating Encounters",
"Common Environments",
"Communication and Languages",
"Companion Items",
"Comparison",
"Compete Alone",
"Complex Hazards",
"Complex Rolls",
"Complications",
"Composition of Outer Space",
"Concept and Role",
"Concept",
"Consequences",
"Consistency and Fairness",
"Constant Abilities",
"Constant and Automatic Abilities",
"Constant and Automatic Damage",
"Consumables",
"Cooperation",
"Corruption",
"Cosmology",
"Cost of Living",
"Counteracting a Magical Hazard",
"Cover",
"Craft Requirements",
"Craft",
"Crafting Items",
"Crafting a Scroll",
"Crafting a Wand",
"Crafting with Precious Materials",
"Creating an Artifact",
"Creative Collaboration",
"Creature Identification",
"Crowds",
"Cultural Hallmarks",
"Currency",
"Currents and Flowing Water",
"Cursed Items",
"Curses",
"DCs",
"Daily Preparations",
"Damage-Dealing Abilities",
"Damaging a Hazard",
"Deafness or Being Hard of Hearing",
"Dealing with Failure",
"Decentralized Storytelling",
"Deciding to Use a Subsystem",
"Defense Potency",
"Defenses",
"Defensive Abilities",
"Deities",
"Depth of Downtime",
"Desert",
"Design Abilities",
"Design Approach",
"Designing Complex Hazards",
"Designing Intelligent Items",
"Designing Nations",
"Designing Simple Hazards",
"Designing by Type",
"Designing the Library",
"Designing the Map",
"Designing the Stat Block",
"Detect Magic",
"Detecting a Hazard",
"Devastating Attacks",
"Devastation",
"Develop the Concept",
"Devotee Benefits",
"Different Contexts",
"Different Item Levels",
"Different Party Sizes",
"Difficult Terrain",
"Difficulty Classes",
"Dimensions",
"Diminishing Rolls",
"Diminishing Victory Points",
"Disabling a Hazard",
"Discovering a Relic",
"Diseases",
"Disliked",
"Dismissing Activations",
"Disservices",
"Distractions and Interruptions",
"Divine Involvement",
"Divine Rank",
"Divine Statistics",
"Doors",
"Duels",
"Dungeon Crawl",
"Duration",
"Dynamic Encounters",
"Earn Income",
"Earthquakes",
"Economy and Political Stances",
"Edge Points",
"Ejecting a Player",
"Encounter Design",
"Encounter Locations",
"Encounters During Travel",
"Encounters",
"Ending Chases",
"Ending the Campaign",
"Ending the Duel",
"Ending the Encounter",
"Enemy Motivations",
"Environment",
"Environmental Damage",
"Environmental Hazards",
"Epic Campaign",
"Etched",
"Events",
"Evocative Environments",
"Evolving Battlefields",
"Existing Activities",
"Experience Points",
"Exploration Activities",
"Extended Campaign",
"Extreme Environments",
"Extreme Increases",
"Extreme Retraining",
"Extremism",
"Failing Forward",
"False Information",
"Fatigue",
"Favors",
"Fill in the Numbers",
"Fissures",
"Flames",
"Fleeing Enemies",
"Fleshing out Exploration",
"Floods",
"Floors",
"Flow of Time",
"Fog",
"Follow the Expert",
"Forest",
"Free Actions",
"Free Archetype",
"Fundamental Runes",
"Gameplay",
"Gates",
"Gather Information",
"Gems & Art Objects",
"Gems",
"Generating Random Hex Maps",
"Getting Lost",
"Gift Saves and Spell Attack Modifiers",
"Government",
"Gravity Traits",
"Gritty Adventure",
"Group Activities",
"Group Attempts",
"Group Composition",
"Group Engagement",
"Group Parity and Party Level",
"Guards",
"Hated",
"Hazard Experience",
"Hazard Format",
"Hazard Types",
"Hazardous Terrain",
"Hazards in Combat",
"Hazards",
"Heat",
"Hedges",
"Held Items",
"Held",
"Hero Points",
"Hexploration",
"High Adventure",
"History",
"Hit Points",
"Horror",
"House Rules",
"How to Use This Book",
"Hunted",
"I Need Items!",
"Ice",
"Idea Farm",
"Identify Magic, Identify Alchemy, or Learn a Spell",
"If the PCs Get Stuck",
"Ignored",
"Immunities, Weaknesses, and Resistances",
"Important Items",
"Improvisation",
"Improvising New Activities",
"Individual Activities",
"Infiltration",
"Influence Stat Blocks",
"Influence",
"Inhabitant or Intruder?",
"Initial Proficiencies",
"Initiative and Actions",
"Initiative and Dueling Actions",
"Initiative with Hidden Enemies",
"Innate Spells",
"Inner Sphere Planes",
"Instruction and Costs",
"Intelligent Item Rules",
"Intelligent Items",
"Intrigue",
"Introduction",
"Investigate",
"Investigations",
"Investing Magic Items",
"Investiture",
"Investments",
"Invisible Abilities",
"Item Agency",
"Item Curses",
"Item Effects",
"Item Level",
"Item Prices",
"Item Selection",
"Items",
"I’m Making My Own Adventure",
"I’m Running a Published Adventure",
"I’m a New Game Master",
"Keeping it Varied",
"Landmass",
"Languages",
"Large Groups",
"Lava Bombs",
"Lava Flows",
"Law Enforcement",
"Leadership Events",
"Leadership",
"Ledges",
"Legal Codes",
"Level 0 Characters",
"Level Appropriateness",
"Level",
"Level-Based DCs",
"Liked",
"Limited Activations",
"Limited Tools",
"Linking Adventures",
"Listen to the Players",
"Location, Size, and Population",
"Locations",
"Long Activation Times",
"Long-Term Goals",
"Long-Term Rest",
"Longer Periods of Downtime",
"Looking Up Rules",
"Looking up Rules",
"Magic Scroll",
"Magic Wand",
"Magic Weapons",
"Magic",
"Magical",
"Make the Call",
"Making Relic Seeds",
"Manipulate Activations",
"Mapping a Settlement",
"Mapping a World",
"Maps and Miniatures",
"Maps and Terrain",
"Marketplaces",
"Material Statistics",
"Materials",
"Mayhem",
"Measuring Success and Progress",
"Metagaming",
"Method of Exposure",
"Military Adventure",
"Minimum Proficiency",
"Misdirection",
"Missing Limbs and Mobility",
"Modes of Play",
"Momentary Magic",
"Money during Long Periods of Downtime",
"Money in Downtime",
"Morale",
"Morphic Traits",
"Motivations",
"Mountain",
"Mounted Combat",
"Movement and Heading",
"Moving in Wind",
"Multiple Point Subsystems",
"Multiple Types",
"Mystery",
"NPC Limitations",
"NPCs and Organizations",
"Naming Your Victory Points",
"Narrative Collaboration",
"Nation Stat Block",
"Nations of Lost Omens",
"Nations",
"Natural Disasters",
"Navigating",
"Non-Combat Level",
"Non-Combat XP",
"Objectionable Content",
"Objective",
"Obstacles and DCs",
"Obstacles in Play",
"Obstacles",
"Offense",
"Oils",
"One-Shot",
"Opponent Synergy",
"Opportunities",
"Organization Levels",
"Organization NPCs",
"Organizations, Churches, and Factions",
"Other Types of Treasure",
"Outer Sphere Planes",
"Overcharging a Wand",
"PC Preparations",
"PC-style Build",
"Pacing Game Sessions",
"Pacing",
"Pantheons",
"Party Size",
"Pathfinder Society Organized Play",
"Pathfinder Society",
"Perception Potency",
"Perception and Senses",
"Perception",
"Piloting Actions",
"Piloting Checks",
"Piloting a Vehicle",
"Placing Characters on the Map",
"Plains",
"Planar Adventure",
"Planar Essence Traits",
"Planar Stat Blocks",
"Planar Traits",
"Planetary Basics",
"Planets and Moons",
"Planning a Session",
"Player Goals",
"Player Motivations",
"Player Needs",
"Playing out a Downtime Day",
"Playing with Free Archetypes",
"Populating Hexes",
"Portcullises",
"Potions",
"Power Imbalances",
"Power Level",
"Power Structures",
"Precious Material Armor",
"Precious Material Shields",
"Precious Material Weapons",
"Precious Materials",
"Precipitation",
"Preparation Activities",
"Prepared Spellcasters",
"Prepared and Spontaneous Spells",
"Preparing Adventures",
"Preparing a Staff",
"Price",
"Problematic Players",
"Proficiency without Level",
"Property Runes",
"Propulsion",
"Published Adventures",
"Pulled",
"Push and Pull",
"Pyroclastic Flows",
"Random Encounters",
"Rarity and Power",
"Rarity",
"Reaction Damage",
"Reaction or Free Action",
"Reactive Abilities",
"Reading Items",
"Ready",
"Recall Knowledge",
"Reckless Piloting",
"Recurring Villains",
"Regeneration and Healing Abilities",
"Relic Aspects",
"Relic Gifts",
"Relics",
"Religion",
"Repairing a Hazard",
"Reputation",
"Reputations",
"Research",
"Resetting a Hazard",
"Resolving Problems",
"Respecting the Character",
"Resting",
"Retraining",
"Revered",
"Review",
"Rewards",
"Rewinding",
"Rituals",
"Roleplaying Investigations",
"Roleplaying NPCs",
"Romantic Adventure",
"Rooftops",
"Routine",
"Rowed",
"Rubble",
"Rune Formulas",
"Runes",
"Running Downtime",
"Running Encounters",
"Running Exploration",
"Running Hexploration",
"Running Leadership",
"Running Reputation",
"Running a Chase",
"Running a Session",
"Running an Influence Encounter",
"Running the Encounter",
"Running your Subsystem",
"Safety Tools",
"Sample Obstacles",
"Sample Settlement Abilities",
"Sand",
"Sandstorms",
"Saving Throw Potency",
"Saving Throws",
"Saying “Yes, But”",
"Scaling out of Usefulness",
"Scenes within Exploration",
"Scope Trait",
"Scope of Changes",
"Scroll Statistics",
"Scrolls",
"Search",
"Searching for Traps",
"Secondary Objectives",
"Secret Checks",
"Seek",
"Sense Direction",
"Sense Motive",
"Senses",
"Sensory Differences",
"Session Zero",
"Set Encounters",
"Setting DCs",
"Setting Obstacle DCs",
"Setting Up a Duel",
"Setting Your Scale",
"Setting a Party Order",
"Setting the Scene",
"Settlement Adventures",
"Settlement Stat Block",
"Settlements in a Game",
"Settlements of Lost Omens",
"Settlements",
"Sewer Gas",
"Sewers",
"Shape",
"Shield Rune",
"Shields",
"Shortcuts and Split Paths",
"Simple DCs",
"Simple Hazards",
"Size and Traits",
"Size, Space, and Capacity",
"Skill Abilities",
"Skill Potency",
"Skills",
"Slopes",
"Small Groups",
"Smoke",
"Snow",
"Social Encounters",
"Social Skills",
"Social Spillover",
"Societal Benchmarks",
"Soil Liquefaction",
"Solar System",
"Special Abilities",
"Special Battles and Movement",
"Special Circumstances",
"Special Class Features",
"Special Considerations",
"Special Modifiers",
"Specialty Wands",
"Specific Actions",
"Specific Cursed Items",
"Specific Intelligent Items",
"Specific Magic Armor",
"Specific Magic Weapons",
"Specific Shields",
"Speed of Play",
"Speed",
"Spell DC and Spell Attack Modifier",
"Spellcasting Duels",
"Spells",
"Splash Trait",
"Splitting and Combining Movement",
"Spontaneous Spellcasters",
"Stairs",
"Stakes and Consequences",
"Stalagmites and Stalactites",
"Starting Elements",
"Starting Encounters",
"Starting Money",
"Starting a Session",
"Starting at a Higher Level",
"Starting the Campaign",
"Starting the Encounter",
"Starvation and Thirst",
"Staves",
"Stealth and Disable",
"Stealth or Stealth DC",
"Story Arcs",
"Story Points",
"Storytelling",
"Streets",
"Strike Attack Bonus",
"Strike Damage",
"Strikes",
"Structures",
"Styles",
"Subjugation",
"Subsist",
"Success and Failure",
"Surprise Attacks",
"Sustaining Activations",
"Swamp",
"Switching out of Hexploration",
"Take Cover",
"Take Time for Review",
"Talismans",
"Tasks and Events",
"Technology",
"Temperature",
"Terrain",
"The Basics",
"The Darklands",
"The Etching Process",
"The Four Rarities",
"The Game Master",
"The Great Beyond",
"The Inner Sea Region",
"The Multiverse",
"The Next Campaign",
"The Pathfinder Baseline",
"The Planes",
"The Solar System",
"The Spotlight",
"The Universe",
"The World",
"Theme and Feeling",
"Themes",
"Theology",
"Threats",
"Thunderstorms",
"Time Pressure",
"Time Traits",
"Time",
"To Create or Adapt",
"Top Down",
"Tornadoes",
"Total Party Kills",
"Track",
"Train an Animal",
"Trait Abilities",
"Traits",
"Transferring Runes",
"Transitive Planes",
"Trappings of Power",
"Travel Speed",
"Travel",
"Treasure and Rarity",
"Treasure by Encounter",
"Treasure by Level",
"Treasure for New Characters",
"Treasure",
"Trees",
"Tremors",
"Triggering a Hazard",
"Tsunamis",
"Types of Chases",
"Uncontrolled Vehicles",
"Underground",
"Undergrowth",
"Understanding Statistics",
"Understanding and Choosing Statistics",
"Underwater Visibility",
"Unusual Group Sizes",
"Urban",
"Usage",
"Using Items",
"Variant Rules",
"Variety",
"Varying Statistics",
"Vehicle Basics",
"Vehicle Momentum",
"Vehicle Statistics",
"Vehicles in Combat",
"Vehicles",
"Vents",
"Victory Point Subsystem Structures",
"Victory Points",
"Villain Goals",
"Visibility",
"Visual Aids",
"Volcanic Eruptions",
"Walls",
"Wand Statistics",
"Wands",
"Watches and Surprise Attacks",
"Wild Weather",
"Wildfires",
"Will Save",
"Wind",
"Wondrous Consumables",
"World Building",
"Worn Items",
"Worn",
"XP Awards",
"XP Budget",
"Your Own Adventures"
]

export const mc = [
    "Adjusting Creatures",
"Combat Power",
"Elite Adjustments",
"Gear",
"Introduction",
"Languages",
"Playing Creatures",
"Reading Creature Statistics",
"Roleplaying Creatures",
"Skills, Perception, and Proficiency",
"Weak Adjustments"
]

// const pc2 = [
//     "Alchemical Archetypes",
// "Temporary Items",
// ]

function getNonUniqueValues(arr:string[]) {
    const seen = new Set();
    const duplicates = new Set();
    arr.forEach(item => {
        if (seen.has(item)) {
            duplicates.add(item);
        } else {
            seen.add(item);
        }
    });
    return arr.filter(item => duplicates.has(item));
}

export const resultARRAY = getNonUniqueValues(pc.concat(gmc));

export const sortDate = (a: string, b:string, direction?: 'asc'|'desc') =>{
    if (direction==='asc') {
        return new Date(a).getTime() - new Date(b).getTime()
    } else {
        return new Date(b).getTime() - new Date(a).getTime()
    }
}

